spring:
    datasource:
        jndi-name: jdbc/aegaeon
    thymeleaf:
        cache: false
        mode: HTML
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc:
        static-path-pattern: /resources/**
    messages:
        encoding: UTF-8 
flyway:
    baseline-version: 1
    check-location: false
    enabled: true
    locations: classpath:db/mysql
    out-of-order: true
