spring:
    datasource:
        jndi-name: jdbc/aegaeon
    thymeleaf:
        cache: false
        mode: HTML
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc:
        static-path-pattern: /resources/**
        throw-exception-if-no-handler-found: true
    messages:
        encoding: UTF-8 
    jackson:
        default-property-inclusion: non_null
flyway:
    enabled: false
    baseline-version: 1
    check-location: false
    locations: classpath:db/mysql
    out-of-order: true
aegaeon:
    modules:
        oauth: true
        login: true
        home: false
        account: false
        discovery: false
        admin: false
        introspect: true
        information: true
        
